library(tidyverse)
library(readr)
german_credit_names <- c(c("CheckingAccountStatus", 
                           "Duration", 
                           "CreditHistory", 
                           "Purpose", 
                           "Amount", 
                           "SavingsAccountBonds", 
                           "EmploymentDuration", 
                           "InstallmentRatePercentage", 
                           "Personal", 
                           "OtherDebtorsGuarantors", 
                           "ResidenceDuration", 
                           "Property", 
                           "Age", 
                           "OtherInstallmentPlans", 
                           "Housing", 
                           "NumberExistingCredits", 
                           "Job", 
                           "NumberPeopleMaintenance", 
                           "Telephone", 
                           "ForeignWorker", 
                           "Class"))
data_url <- "http://archive.ics.uci.edu/ml/machine-learning-databases/statlog/german/german.data"
german_credit <- 
  read_table2(data_url, 
              col_names = german_credit_names)
factor_key = list("A11" = "lt.0",
                  "A12" = "0.to.200",
                  "A13" = "gt.200",
                  "A14" = "no checking account", 
                  "A30" = "no credits taken/ all credits paid back duly", 
                  "A31" = "all credits at this bank paid back duly", 
                  "A32" = "existing credits paid back duly till now", 
                  "A33" = "delay in paying off in the past", 
                  "A34" = "critical account/ other credits existing (not at this bank)", 
                  "A40" = "car (new)", 
                  "A41" = "car (used)", 
                  "A42" = "furniture/equipment", 
                  "A43" = "radio/television", 
                  "A44" = "domestic appliances", 
                  "A45" = "repairs", 
                  "A46" = "education", 
                  "A47" = "(vacation - does not exist?)", 
                  "A48" = "retraining", 
                  "A49" = "business", 
                  "A410" = "others",
                  "A61" = "lt.100",
                  "A62" = "100.to.500",
                  "A63" = "500.to.1000",
                  "A64" = "gt.1000",
                  "A65" = "unknown/ no savings account", 
                  "A71" = "unemployed", 
                  "A72" = "lt.1",
                  "A73" = "1.to.4",
                  "A74" = "4.to.7",
                  "A75" = "gt.7",
                  "A91" = "male:divorced/separated", 
                  "A92" = "female:divorced/separated/married", 
                  "A93" = "male:single", 
                  "A94" = "male:married/widowed", 
                  "A95" = "female:single", 
                  "A101" = "none", 
                  "A102" = "co-applicant", 
                  "A103" = "guarantor", 
                  "A121" = "RealEstate",
                  "A122" = "Insurance",
                  "A123" = "CarOther",
                  "A124" = "Unknown",
                  "A141" = "bank", 
                  "A142" = "stores", 
                  "A143" = "none", 
                  "A151" = "rent", 
                  "A152" = "own", 
                  "A153" = "for free", 
                  "A171" = "unemployed/ unskilled - non-resident", 
                  "A172" = "unskilled - resident", 
                  "A173" = "skilled employee", 
                  "A174" = "Management/SelfEmp/HighlyQualified", 
                  "A191" = "none", 
                  "A192" = "yes, registered under the customers name", 
                  "A201" = "yes", 
                  "A202" = "no")

german_credit <- 
  german_credit %>% 
  mutate_if(is.character, recode, !!!factor_key) %>% 
  mutate(Class = recode(Class, `1` = 'Good', `2` = 'Bad'))

