---
title: "i have my data..."
subtitle: "NOW WHAT?"
author: "Caroline Ledbetter"
date: "`r paste(Sys.Date())`"
output: 
  xaringan::moon_reader:
    css: ["default", "default-fonts", "../css/all.min.css", "../css/custom.css"]
    nature:
      highlightStyle: github
      highlightLines: true
    seal: false
params:
  slides: "now_what/"
  github: "now_what"
---
class: title-slide, center, middle
background-image: 
background-size: contain
background-color:black

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
knitr::opts_chunk$set(warning = FALSE, 
                      message = FALSE, 
                      collapse = TRUE,
                      fig.retina = 3)
#library(tidyverse) # load tidyverse package
#load(file = 'demo_data.Rdata')
```


## `r rmarkdown::metadata$title`
# `r rmarkdown::metadata$subtitle`

### `r rmarkdown::metadata$author`

### `r Sys.Date()` 

#### <i class="fas fa-images"></i> `r paste0('https://slides.carolineledbetter.us/', params$slides)` 
<i class="fab fa-github-square"></i> `r paste0('https://github.com/ledbettc/slides/tree/master/', params$github)`
---
class:middle
name: details
<!-- edit slides and github repo in the YAML above -->

.intro[
#Find me at: 
]
.intro-right[
<i class = "fas fa-globe"></i> carolineledbetter.us  
<i class = "far fa-envelope"></i>
carolineledbetter@yahoo.com  
<i class="fab fa-github"></i>
 @ledbettc  
<i class="fab fa-twitter"></i>
@C_line_sealion
]

---
layout: true
background-image: 
background-size: contain
.footer[`r paste0('https://slides.carolineledbetter.us/', params$slides)`]
---
class:center, top

.header[**The Data Analysis Plan**]

--

.left[
**Hypothesis:**  
{{content}}
]

--

Individuals with MDIS have higher rates of chronic pain post spinal surgery.  
{{content}}

--

**Inclusion Criteria:**  
{{content}}


--

Spinal procedure as defined by procedure codes  
{{content}}

--

**Exposure:**  
{{content}}


--

Multiple Drug Intolerance Syndrome  
{{content}}

--

**Outcome:**
{{content}}

--

Chronic Pain  
{{content}}

--

**Covariates:**  
{{content}}

--

Race, Ethnicity, Sex, Financial Class
{{content}}

---
class: inverse, center
# Sample Plan  

<a href="https://slides.carolineledbetter.us/now_what/img/data_analysis_plan.pdf" target="_blank">data_analysis_plan.pdf</a>

---
class:top

.header[ .center[**Flat File vs Relational Data Tables**]  ]

--

.big[
.pull-left[
**Flat File**   
<br>
* self-contained   
* may duplicate information
]
]

--

.big[
.pull-right[
**Relational Data Tables**
* can be many tables
* connected keys (relations)
]
]

---
class: center, middle, inverse

# A tale of four tables...


---
  
Person:
* Person ID
* Race
* Ethnicity
* Sex
* Financial Class

Encounter:
* Person ID
* Encounter ID
* Days from DOB to encounter
* Encounter Type
* Department Name

Diagnoses:
* Persion ID
* Encounter ID
* Code
* Code Description
* Source
* Days from DOB to ICD Code

Inpatients Meds:


---

class:center, middle
<strong>
<blockquote class="twitter-tweet">
<p lang="en" dir="ltr">“EDA is never done. You just die” as 
<a href="https://twitter.com/RohanAlexander?ref_src=twsrc%5Etfw">@RohanAlexander</a> 
told an unsuspecting student <a href="https://t.co/0Lt8LRpkg7">https://t.co/0Lt8LRpkg7</a>
</p>
&mdash; Monica Alexander (@monjalexander) 
<a href="https://twitter.com/monjalexander/status/1234112608837537792?ref_src=twsrc%5Etfw">March 1, 2020</a>
</blockquote> 
<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
</strong> 

---
layout:false

#Resources:   

.resources[
]
---
<!-- last slide go back to details slide -->
#[Return to Contact Info](#details)

